import type { LexicalAnalysis, HeuristicIndicator } from '../../types/scanner.js';
import { getApexDomain } from '../../utils/urlHelper.js';

// Top-Level Domains with statistically high malware/phishing abuse rates
export const HIGH_ABUSE_TLDS = new Set([
  'zip', 'mov', 'top', 'xyz', 'click', 'work', 'loan', 'cf', 'gq', 'ml', 'ga', 'tk',
  'fit', 'buzz', 'rest', 'surf', 'cam', 'sbs', 'beauty', 'icu', 'club', 'quest',
  'cfd', 'mom', 'monster', 'online', 'site', 'live', 'support', 'space', 'shop'
]);

/**
 * Calculates the Shannon Entropy of a given string in bits per symbol.
 * High entropy (> 3.8 for domains) indicates randomized / DGA / obfuscated text.
 */
export function calculateShannonEntropy(str: string): number {
  if (!str || str.length === 0) return 0;
  const frequencies = new Map<string, number>();
  for (const char of str) {
    frequencies.set(char, (frequencies.get(char) || 0) + 1);
  }
  let entropy = 0;
  const len = str.length;
  for (const count of frequencies.values()) {
    const p = count / len;
    entropy -= p * Math.log2(p);
  }
  return Number(entropy.toFixed(2));
}

/**
 * Evaluates lexical and URL structural features.
 */
export function analyzeLexicalStructure(urlObj: URL): {
  analysis: LexicalAnalysis;
  indicators: HeuristicIndicator[];
} {
  const hostname = urlObj.hostname.toLowerCase();
  const pathname = urlObj.pathname.toLowerCase();
  const search = urlObj.search.toLowerCase();
  const fullUrl = urlObj.href;

  // Raw IPv4 or IPv6 detection
  const isIpv4 = /^(\d{1,3}\.){3}\d{1,3}$/.test(hostname.split(':')[0]);
  const isIpv6 = hostname.startsWith('[') || (hostname.includes(':') && !hostname.includes('.'));
  const hasRawIp = isIpv4 || isIpv6;

  const apex = hasRawIp ? hostname : getApexDomain(hostname);
  const parts = hostname.split('.');
  const tld = hasRawIp ? 'N/A' : (apex.split('.').pop() || '');
  const isAbuseTld = !hasRawIp && HIGH_ABUSE_TLDS.has(tld);

  // Subdomain calculation (excluding apex domain parts)
  const apexParts = apex.split('.');
  const subdomains = hasRawIp ? [] : parts.slice(0, Math.max(0, parts.length - apexParts.length));
  const subdomainCount = subdomains.length;

  // Shannon Entropy
  const hostnameEntropy = calculateShannonEntropy(hostname.replace(/\./g, ''));
  const pathEntropy = calculateShannonEntropy((pathname + search).replace(/[/?.=&_-]/g, ''));

  // Special character counts
  const hyphenCount = (hostname.match(/-/g) || []).length;
  const digitCount = (hostname.match(/\d/g) || []).length;
  const hasAtSymbol = Boolean(urlObj.username) || (fullUrl.includes('@') && fullUrl.indexOf('@') < fullUrl.indexOf(hostname));

  const analysis: LexicalAnalysis = {
    hostnameEntropy,
    pathEntropy,
    subdomainCount,
    subdomains,
    hasRawIp,
    tld,
    isAbuseTld,
    urlLength: fullUrl.length,
    hasAtSymbol,
    hyphenCount,
    digitCount,
  };

  const indicators: HeuristicIndicator[] = [];

  // 1. Raw IP Hostname Check
  if (hasRawIp) {
    indicators.push({
      id: 'lex-raw-ip',
      module: 'LEXICAL',
      title: 'Raw IP Address Hostname',
      description: `Target uses numeric IP (${hostname}) instead of a registered domain name. Characteristic of direct C2 nodes and disposable phishing hosts.`,
      severity: 'CRITICAL',
      points: 40,
      passed: false,
    });
  } else {
    indicators.push({
      id: 'lex-raw-ip',
      module: 'LEXICAL',
      title: 'Standard Registered Domain Format',
      description: 'Host resolves via standard domain naming system rather than a raw IP address.',
      severity: 'INFO',
      points: 0,
      passed: true,
    });

    // 2. High-Abuse TLD Check (only applies to registered domains)
    if (isAbuseTld) {
      indicators.push({
        id: 'lex-abuse-tld',
        module: 'LEXICAL',
        title: `High-Risk Top-Level Domain (.${tld})`,
        description: `The .${tld} top-level extension has elevated historical abuse rates for fraudulent landing pages and malware hosting.`,
        severity: 'HIGH',
        points: 20,
        passed: false,
      });
    } else {
      indicators.push({
        id: 'lex-abuse-tld',
        module: 'LEXICAL',
        title: `Reputable Top-Level Domain (.${tld})`,
        description: `Domain extension .${tld} is not flagged on the high-abuse TLD watch list.`,
        severity: 'INFO',
        points: 0,
        passed: true,
      });
    }
  }

  // 3. Shannon Entropy Check
  if (hostnameEntropy >= 3.85 && hostname.length >= 10 && !hasRawIp) {
    indicators.push({
      id: 'lex-high-entropy',
      module: 'LEXICAL',
      title: `High Shannon Entropy (${hostnameEntropy} bits)`,
      description: `Host string demonstrates high algorithmic randomness. Frequently generated by Domain Generation Algorithms (DGA) or anti-block cloner tools.`,
      severity: 'HIGH',
      points: 25,
      passed: false,
    });
  } else {
    indicators.push({
      id: 'lex-high-entropy',
      module: 'LEXICAL',
      title: `Normal Shannon Entropy (${hostnameEntropy} bits)`,
      description: 'Character distribution matches typical natural language or deliberate corporate domain naming.',
      severity: 'INFO',
      points: 0,
      passed: true,
    });
  }

  // 4. Subdomain Stacking / Depth Check
  if (subdomainCount >= 3) {
    indicators.push({
      id: 'lex-subdomain-stacking',
      module: 'LEXICAL',
      title: `Excessive Subdomain Stacking (${subdomainCount} subdomains)`,
      description: `Stacked subdomains (${subdomains.join('.')}) deceive mobile users whose address bars truncate long hosts.`,
      severity: 'MEDIUM',
      points: 15,
      passed: false,
    });
  }

  // 5. Embedded Credentials / Userinfo Trick
  if (hasAtSymbol) {
    indicators.push({
      id: 'lex-userinfo-at',
      module: 'LEXICAL',
      title: 'Obfuscated @ Symbol / Embedded Credentials',
      description: 'URL embeds an @ symbol before the hostname to masquerade the real server address.',
      severity: 'CRITICAL',
      points: 40,
      passed: false,
    });
  }

  // 6. Excessive Hyphens / Token Masquerade
  if (hyphenCount >= 3) {
    indicators.push({
      id: 'lex-hyphen-stacking',
      module: 'LEXICAL',
      title: `Excessive Hyphenation (${hyphenCount} hyphens)`,
      description: 'Multiple hyphens are commonly used to concatenate reputable brand names with malicious words.',
      severity: 'LOW',
      points: 10,
      passed: false,
    });
  }

  // 7. Abnormally Long URL
  if (fullUrl.length > 120) {
    indicators.push({
      id: 'lex-length-anomaly',
      module: 'LEXICAL',
      title: `Abnormally Long URL (${fullUrl.length} characters)`,
      description: 'Excessively long URLs are often used to conceal target parameters or overflow scanner inspection buffers.',
      severity: 'LOW',
      points: 10,
      passed: false,
    });
  }

  return { analysis, indicators };
}
