import React, { useState } from 'react';
import { X, Copy, Check, Share2 } from 'lucide-react';
import type { ScanResult } from '../types/scanner.js';

interface ReportModalProps {
  result: ScanResult | null;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ result, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!result) return null;

  const {
    verdict,
    targetDomain,
    apexDomain,
    riskLevel,
    riskScore,
    lexical,
    homoglyph,
    dom,
    threatIntel,
    rdap,
    ssl,
    indicators,
  } = result;

  const flaggedList = indicators.filter((i) => !i.passed);

  const generatedReportText = `[SENTINELLINK DETERMINISTIC OSINT THREAT REPORT]
Date: ${new Date(result.timestamp).toUTCString()}
Target Domain: ${targetDomain} (Apex: ${apexDomain})
Initial Link: ${result.extractedUrl}
Final Destination: ${result.finalUrl}

SECURITY VERDICT: ${riskLevel}
Composite Threat Score: ${riskScore}/100
Attack Classification: ${verdict.attackVector}

EXECUTIVE SUMMARY:
${verdict.plainEnglishSummary}

POTENTIAL IMPACT:
${verdict.dangerExplanation}

CORE OSINT & HEURISTIC SIGNALS:
- Shannon Entropy: ${lexical.hostnameEntropy} bits (Subdomains: ${lexical.subdomainCount}, Abuse TLD: ${lexical.isAbuseTld ? 'Yes' : 'No'})
- Homoglyph / Typosquatting: ${homoglyph.isTyposquat ? `YES (Impersonating ${homoglyph.matchedBrand}, edit distance ${homoglyph.levenshteinDistance ?? 'N/A'})` : 'None detected'}
- DOM / Forms: ${dom.hasPasswordInput ? (dom.hasUnencryptedPasswordInput ? 'Plaintext Password Input (Insecure HTTP)' : 'Password Input Field Present') : 'Clean (No credentials)'}, Hidden Iframes: ${dom.hiddenIframeCount}
- Threat Intel Feeds: ${threatIntel.knownThreatListMatched ? `Blacklist Matched (${threatIntel.urlhausThreat || threatIntel.phishtankTarget})` : 'Clean (Not listed on URLhaus/PhishTank)'}
- Domain Age: ${rdap.domainAgeDays !== undefined ? `${rdap.domainAgeDays} days (Registered: ${rdap.registrationDate || 'Unknown'})` : 'Private / Hidden'}
- Registrar: ${rdap.registrar || 'Private'}
- SSL Status: ${ssl.hasSsl ? (ssl.valid ? `Valid (${ssl.issuerOrg || 'TLS'})` : 'Invalid / Untrusted') : 'None (Plaintext HTTP)'}
- Redirection Hops: ${result.redirects.length}

FLAGGED THREAT CHECKS (${flaggedList.length} indicators):
${
  flaggedList.length > 0
    ? flaggedList
        .map((f, i) => `${i + 1}. [${f.module}] ${f.title} (+${f.points} pts) - ${f.description}`)
        .join('\n')
    : 'None. All security heuristics passed.'
}

RECOMMENDED DEFENSIVE ACTIONS:
${verdict.recommendedActions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

Generated by SentinelLink Deterministic Security & OSINT Analysis Engine.`;

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedReportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-sm">
      <div className="relative w-full max-w-2xl rounded-xl border border-slate-800 bg-slate-900 p-6 shadow-2xl">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3 mb-4">
          <div className="flex items-center gap-2">
            <Share2 className="h-4 w-4 text-amber-400" />
            <h3 className="text-sm font-bold text-slate-100 uppercase tracking-wide">
              Export Security Threat Report
            </h3>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors cursor-pointer"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <p className="text-xs text-slate-400 mb-3">
          Share this transparent incident brief with your IT security desk, team members, or family to warn them against opening this link.
        </p>

        <textarea
          readOnly
          value={generatedReportText}
          rows={12}
          className="w-full rounded-lg border border-slate-800 bg-slate-950 p-3.5 font-mono text-xs text-slate-200 focus:outline-none select-all leading-relaxed"
        />

        <div className="mt-4 flex items-center justify-between">
          <span className="text-[11px] text-slate-500 font-mono">
            Deterministic Heuristic Format · Ready to paste
          </span>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="rounded-lg border border-slate-800 bg-slate-900 px-4 py-2 text-xs font-semibold text-slate-300 hover:bg-slate-800 transition-colors cursor-pointer"
            >
              Close
            </button>
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded-lg bg-amber-500 px-4 py-2 text-xs font-semibold text-slate-950 hover:bg-amber-400 transition-colors cursor-pointer"
            >
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied to Clipboard' : 'Copy Full Report'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
